name: R

on:
  workflow_dispatch:
  schedule:
    - cron: '30 14 31 8 *'



env:
  PYTHONUNBUFFERED: 1

jobs:
  extract-telemetry:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Cache uv dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/uv
            ~/.uv
          key: ${{ runner.os }}-uv-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Install dependencies with uv
        run: |
          uv pip install --system -r requirements.txt

      - name: Configure Git
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "action@github.com"
          # Minimal Git configuration for performance
          git config --global core.compression 0
          git config --global core.preloadIndex true
          git config --global core.fsyncMethod batch

      - name: Run Telemetry Extraction
        run: python telR.py
        env:
          GITHUB_ACTIONS: "true"

      - name: Commit and push changes
        run: |
          # Fast pull strategy
          git pull --no-rebase --no-edit origin main || true

          # Add all changes
          git add .

          # Only commit if there are changes
          if [[ "$(git status --porcelain)" != "" ]]; then
              git commit -m "Update F1 telemetry data [skip ci]" -a
              git push origin main
          else
              echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
